### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jake87240** [spinfal/enmity-plugins#26]
**Describe the bug**
Message logger does not save anything to the log or after restarting enmity

**To Reproduce**
1. See deleted or edited message
2. open log nothing there
3. Restart enmity and it's out of the chat

**Expected behavior**
Deleted chats save to log. Deleted chats stay in chat on app reload

**Smartphone (please complete the following information):**
 - Device: Iphone 12 mini
 - OS: iOS 15.7.1
 - Discord Version: 199.0

**Comment by spinfal** [comment]
sorry for the late response, the edit/delete log not staying in chat is normal behavior. however the edits/deletes not showing up in logs is not normal; could you please edit and delete a message, then save your discord debug logs to a file and dm the file to me on discord. my username is: `spin.js`
