### ISSUE TITLE
[BUG] NoDelete broken V140 dispatch undefined

### ISSUE THREAD

**Issue by JustRadical** [spinfal/enmity-plugins#3]
**Describe the bug**
NoDelete does not start up properly "Cannot read property 'dispatch' of undefined"

**To Reproduce**
1. Install NoDelete
2. Open Enmity

**Expected behavior**
I expected the plugin to function

**Screenshots**
![IMG_1599](https://user-images.githubusercontent.com/66682497/188322745-95ac600f-c6a8-417a-ab3d-506088adfaaf.png)

**Debug Logs Error(s)**
Screenshot of logs and/or a link to your exported Debug Logs file.
![IMG_1600](https://user-images.githubusercontent.com/66682497/188322842-366a7a2b-338b-43a7-8edf-51291663ee69.png)

**Smartphone (please complete the following information):**
 - Device: iPhone14,2 (13 Pro)
 - OS: iOS 16
 - Discord Version: Enmity 140.0

**Additional context**

Debug Info:
> Enmity: 5b6f673
> Discord: 140.0 (34452)
> Device: iPhone14,2
> System: 16.0

**Comment by spinfal** [comment]
Heyo, it's recommended that you [update your Enmity to the latest IPA](https://github.com/enmity-mod/tweak/releases/latest). Can you please do so before I try to make plugins work on older Discord versions?

**Comment by justradical** [comment]
Yeah that was the issue, have had trouble with AltStore recently.
