### ISSUE TITLE
[BUG] - NoDelete

### ISSUE THREAD

**Issue by 35e** [spinfal/enmity-plugins#8]
**Describe the bug**
The bug is with the message logger. If you remove an embed for example from a bot the whole discord get bugged. Switching chats doesn't work anymore and typing also is broken you need to restart discord for it to work again.

**To Reproduce**
1. Go to a bot that can output embeds and has an option to remove them. tip.cc#7731 has an embed if you type '$bals'.

2. Click on the 'X' at the bottom of the embed.
3. Now discord is bugged and you can't switch chats or type anymore.

**Expected behavior**
Being able to switch chats and type..

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.1
 - Discord Version 151

**Comment by spinfal** [comment]
thanks for creating this issue; it has been fixed in version `2.4.10`
(dupe issue #9 created by me)
